development:
  adapter: postgresql
  encoding: unicode
  database: live_from_ny_development
  pool: 5
  username: pamorgan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: live_from_ny_test
  pool: 5
  username: pamorgan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: live_from_ny_production
  pool: 5
  username: pamorgan
  password:
